"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Lang = "en" | "hi" | "bn" | "ta" | "te" | "mr" | "gu" | "kn" | "ml" | "pa";

export const languages: { code: Lang; label: string; nativeName: string; speechLocale: string }[] = [
  { code: "en", label: "English", nativeName: "English", speechLocale: "en-IN" },
  { code: "hi", label: "Hindi", nativeName: "हिन्दी", speechLocale: "hi-IN" },
  { code: "bn", label: "Bengali", nativeName: "বাংলা", speechLocale: "bn-IN" },
  { code: "ta", label: "Tamil", nativeName: "தமிழ்", speechLocale: "ta-IN" },
  { code: "te", label: "Telugu", nativeName: "తెలుగు", speechLocale: "te-IN" },
  { code: "mr", label: "Marathi", nativeName: "मराठी", speechLocale: "mr-IN" },
  { code: "gu", label: "Gujarati", nativeName: "ગુજરાતી", speechLocale: "gu-IN" },
  { code: "kn", label: "Kannada", nativeName: "ಕನ್ನಡ", speechLocale: "kn-IN" },
  { code: "ml", label: "Malayalam", nativeName: "മലയാളം", speechLocale: "ml-IN" },
  { code: "pa", label: "Punjabi", nativeName: "ਪੰਜਾਬੀ", speechLocale: "pa-IN" },
];

type Dict = Record<string, string>;

const en: Dict = {
  "nav.home": "Home",
  "nav.symptoms": "Symptoms",
  "nav.reports": "Reports",
  "nav.analysis": "Analysis",
  "nav.hospitals": "Hospitals",
  "nav.live": "Live",
  "common.language": "Language",
  "common.loading": "Loading...",
  "common.clear": "Clear",
  "common.stop": "Stop",
  "common.call112": "Call 112",
  "common.emergency112": "112 Emergency",
  "common.emergencyCall112": "Emergency Call 112",
  "common.footer.disclaimer": "For guidance only - not a medical diagnosis",
  "home.badge": "Healthcare navigation for patients",
  "home.title": "Urgent care guidance, made easier for real patients",
  "home.subtitle": "MediRoute AI helps people understand symptoms, read basic reports, and find suitable nearby care without turning every health question into a maze.",
  "home.cta.symptoms": "Check symptoms",
  "home.cta.upload": "Upload report",
  "home.signal.severity": "Symptom severity",
  "home.signal.report": "Report context",
  "home.signal.department": "Care department",
  "home.signal.hospitals": "Nearby hospitals",
  "home.strip.quick": "Built for quick decisions",
  "home.strip.signup": "No signup required",
  "home.strip.input": "Multilingual input",
  "home.strip.disclaimer": "Doctor-aware disclaimer",
  "home.surface": "Product surface",
  "home.surface.title": "Calm interface for stressful moments.",
  "home.surface.copy": "Warm clinic light, soft whites, muted blue-green accents, and direct patient language help the app feel calm during urgent decisions.",
  "home.capability.triage.title": "Triage that feels understandable",
  "home.capability.triage.desc": "Patients get a plain-language read on urgency, risk signs, and what to do before travelling.",
  "home.capability.reports.title": "Reports without medical jargon",
  "home.capability.reports.desc": "Upload prescriptions or lab reports and surface the few points that matter for the next step.",
  "home.capability.routing.title": "Routing based on fit",
  "home.capability.routing.desc": "Hospitals are ranked by distance, department match, and emergency suitability.",
  "home.live": "Live triage",
  "home.live.title": "A realistic care summary, not a magic diagnosis.",
  "home.sample.severity": "Severity",
  "home.sample.severity.value": "Moderate",
  "home.sample.department": "Department",
  "home.sample.department.value": "General medicine",
  "home.sample.route": "Route",
  "home.sample.route.value": "18 min away",
  "home.sample.ask": "Ask about duration, fever, breathing difficulty, and current medication.",
  "home.sample.warning": "Show emergency warning signs before hospital recommendations.",
  "home.sample.guidance": "Keep every recommendation framed as guidance, not diagnosis.",
  "home.workflow.title": "Designed around the moment before care.",
  "home.workflow.copy": "The workflow keeps a human consultation in mind: listen first, summarize clearly, then help the patient move to the right place.",
  "home.workflow.1": "Describe symptoms in natural language",
  "home.workflow.2": "Review severity, first-aid notes, and report context",
  "home.workflow.3": "Pick the care option that is closest and suitable",
  "home.guardrail": "Emergency guardrail",
  "home.guardrail.title": "Clear escalation when AI should step aside.",
  "home.guardrail.call": "For life-threatening symptoms, call 112 immediately.",
  "home.guardrail.copy": "Severe chest pain, breathing difficulty, loss of consciousness, stroke signs, or major injury should bypass AI guidance.",
  "symptoms.topline": "Symptom details",
  "symptoms.title": "Tell us what you are feeling",
  "symptoms.copy": "Speak or type in any language. Keep it simple, like you would explain it to a doctor.",
  "symptoms.mic.listening": "Listening...",
  "symptoms.mic.idle": "Tap to speak",
  "symptoms.mic.activeHelp": "Keep speaking. Tap stop when you are done.",
  "symptoms.mic.help": "Your selected language, English, or mixed language is fine.",
  "symptoms.live": "LIVE",
  "symptoms.type": "Type symptoms",
  "symptoms.placeholder": "Example: Fever since yesterday, headache, weakness, and mild cough. Breathing is normal.",
  "symptoms.quick.fever": "Fever and body ache",
  "symptoms.quick.chest": "Chest pain",
  "symptoms.quick.breath": "Difficulty breathing",
  "symptoms.quick.vomit": "Vomiting and nausea",
  "symptoms.quick.head": "Severe headache",
  "symptoms.quick.stomach": "Stomach pain",
  "symptoms.error.voiceUnsupported": "Voice input is not supported in this browser. Please type your symptoms.",
  "symptoms.error.voice": "Could not capture voice clearly. Please try again or type.",
  "symptoms.error.empty": "Please describe your symptoms first.",
  "symptoms.error.analyze": "Analysis failed. Please try again.",
  "symptoms.submit": "Continue to analysis",
  "symptoms.analyzing": "Analyzing...",
  "symptoms.loading": "Loading intake...",
  "upload.topline": "Medical reports",
  "upload.types": "PDF, JPG, PNG",
  "upload.title": "Upload medical reports",
  "upload.copy": "Add a prescription, lab report, or scan image. We will summarize the important points in simple language.",
  "upload.choose": "Choose files or drag them here",
  "upload.limit": "Up to 6 files",
  "upload.error.nofile": "Please upload at least one file.",
  "upload.error.fail": "Report analysis failed. Please retry.",
  "upload.progress": "Analyzing documents...",
  "upload.submit": "Analyze reports",
  "upload.analyzing": "Analyzing...",
  "analysis.empty.title": "No analysis yet",
  "analysis.empty.copy": "Start with symptoms or upload a report so MediRoute can prepare a care summary.",
  "analysis.empty.cta": "Go to symptom intake",
  "analysis.topline": "Care summary",
  "analysis.title": "Review the triage result before choosing care.",
  "analysis.copy": "This is a structured guidance view. It should support a patient or helper, not replace a clinician.",
  "analysis.findHospitals": "Find hospitals",
  "analysis.emergency": "Emergency level",
  "analysis.department": "Department",
  "analysis.confidence": "AI confidence",
  "analysis.highRisk": "High-risk symptoms should be evaluated urgently. Do not wait for additional AI guidance.",
  "analysis.firstAid": "First-aid steps",
  "analysis.next": "What to do next",
  "analysis.findNearest": "Find nearest hospital",
  "analysis.dashboard": "Open live dashboard",
  "analysis.report.notes": "Report notes",
  "analysis.report.title": "Plain-language report summary",
  "analysis.report.specialist": "Suggested specialist:",
  "analysis.report.points": "Points to note",
  "analysis.report.fallback": "Could not read report summary.",
  "analysis.specialist.fallback": "General Physician",
  "severity.low": "Low risk",
  "severity.moderate": "Moderate risk",
  "severity.high": "High risk",
  "severity.critical": "Critical",
  "hospitals.empty.cta": "Go to symptoms",
  "hospitals.error.noAnalysis": "Please complete symptom or report analysis first.",
  "hospitals.error.noLocation": "Location is not available in this browser.",
  "hospitals.error.fetch": "Could not fetch hospital recommendations.",
  "hospitals.error.permission": "Please enable location access to find nearby hospitals.",
  "hospitals.loading": "Finding nearby hospitals based on your triage result...",
  "hospitals.topline": "Hospital routing",
  "hospitals.title": "Choose nearby care that matches the situation.",
  "hospitals.copy": "Hospitals are ranked by travel time, distance, suitability, and department fit. Confirm availability by phone before travelling when possible.",
  "hospitals.best": "Best match",
  "hospitals.call": "Call hospital",
  "hospitals.navigate": "Navigate",
  "hospitals.recommended": "Recommended",
  "hospitals.rating": "rating",
  "hospitals.mapUnavailable": "Map unavailable",
  "dashboard.error.noTriage": "No active triage. Please analyze symptoms first.",
  "dashboard.error.noLocation": "Location is not available.",
  "dashboard.error.refresh": "Live refresh failed.",
  "dashboard.error.permission": "Please allow location access.",
  "dashboard.loading": "Loading live care dashboard...",
  "dashboard.topline": "Live dashboard",
  "dashboard.title": "Monitor the active triage and care routing.",
  "dashboard.copy": "A compact operational view for the current patient flow. Hospital data refreshes every 30 seconds when location is available.",
  "dashboard.updated": "Updated",
  "dashboard.updating": "Updating...",
  "dashboard.severity": "Severity",
  "dashboard.emergency": "Emergency",
  "dashboard.department": "Department",
  "dashboard.confidence": "Confidence",
  "dashboard.feed": "Nearby hospital feed",
  "dashboard.feed.copy": "Ranked by ETA, distance, and fit.",
  "dashboard.best": "Best",
  "dashboard.route": "Route",
  "dashboard.noHospitals": "No hospitals found yet.",
  "dashboard.routing": "Current routing decision",
  "dashboard.topMatch": "Top match",
  "dashboard.minAway": "min away",
  "dashboard.navigate": "Navigate to hospital",
  "dashboard.noTop": "Top match is not available yet.",
  "dashboard.keepOpen": "Keep this page open during handoff. It refreshes automatically and keeps the latest hospital ranking visible.",
};

const translations: Record<Lang, Partial<Dict>> = {
  en,
  hi: {
    "common.language": "भाषा",
    "common.loading": "लोड हो रहा है...",
    "common.clear": "साफ करें",
    "common.stop": "रोकें",
    "common.call112": "112 पर कॉल करें",
    "common.emergency112": "112 आपातकाल",
    "common.emergencyCall112": "आपातकालीन कॉल 112",
    "common.footer.disclaimer": "केवल मार्गदर्शन के लिए - यह चिकित्सा निदान नहीं है",
    "nav.home": "होम",
    "nav.symptoms": "लक्षण",
    "nav.reports": "रिपोर्ट",
    "nav.analysis": "विश्लेषण",
    "nav.hospitals": "अस्पताल",
    "nav.live": "लाइव",
    "home.title": "तुरंत देखभाल का मार्गदर्शन, हर मरीज के लिए आसान",
    "home.subtitle": "MediRoute AI लक्षण समझने, रिपोर्ट पढ़ने और पास की उचित देखभाल खोजने में मदद करता है।",
    "home.cta.symptoms": "लक्षण जांचें",
    "home.cta.upload": "रिपोर्ट अपलोड करें",
    "home.strip.input": "बहुभाषी इनपुट",
    "symptoms.title": "बताएं आपको क्या महसूस हो रहा है",
    "symptoms.copy": "किसी भी भाषा में बोलें या लिखें। डॉक्टर को जैसे बताते हैं वैसे सरल शब्दों में बताएं।",
    "symptoms.mic.listening": "सुन रहे हैं...",
    "symptoms.mic.idle": "बोलने के लिए टैप करें",
    "symptoms.mic.activeHelp": "बोलते रहें। पूरा होने पर रोकें।",
    "symptoms.mic.help": "चुनी गई भाषा, अंग्रेजी या मिश्रित भाषा चलेगी।",
    "symptoms.type": "लक्षण लिखें",
    "symptoms.placeholder": "उदाहरण: कल से बुखार, सिरदर्द, कमजोरी और हल्की खांसी। सांस सामान्य है।",
    "symptoms.error.voiceUnsupported": "इस ब्राउजर में आवाज इनपुट समर्थित नहीं है। कृपया टाइप करें।",
    "symptoms.error.voice": "आवाज साफ नहीं मिली। फिर कोशिश करें या टाइप करें।",
    "symptoms.error.empty": "कृपया पहले अपने लक्षण बताएं।",
    "symptoms.error.analyze": "विश्लेषण विफल रहा। फिर कोशिश करें।",
    "symptoms.submit": "विश्लेषण पर जाएं",
    "symptoms.analyzing": "विश्लेषण हो रहा है...",
    "upload.title": "मेडिकल रिपोर्ट अपलोड करें",
    "upload.copy": "पर्चा, लैब रिपोर्ट या स्कैन इमेज जोड़ें। हम जरूरी बातें सरल भाषा में बताएंगे।",
    "upload.choose": "फाइल चुनें या यहां खींचें",
    "upload.limit": "अधिकतम 6 फाइलें",
    "upload.error.nofile": "कृपया कम से कम एक फाइल अपलोड करें।",
    "upload.error.fail": "रिपोर्ट विश्लेषण विफल रहा। फिर कोशिश करें।",
    "upload.submit": "रिपोर्ट का विश्लेषण करें",
    "analysis.empty.title": "अभी कोई विश्लेषण नहीं",
    "analysis.empty.copy": "देखभाल सारांश पाने के लिए लक्षण बताएं या रिपोर्ट अपलोड करें।",
    "analysis.empty.cta": "लक्षण इनपुट पर जाएं",
    "analysis.title": "देखभाल चुनने से पहले ट्रायाज परिणाम देखें।",
    "analysis.copy": "यह मार्गदर्शन है। यह डॉक्टर की जगह नहीं लेता।",
    "analysis.findHospitals": "अस्पताल खोजें",
    "analysis.highRisk": "उच्च जोखिम वाले लक्षणों की तुरंत जांच जरूरी है। इंतजार न करें।",
    "analysis.firstAid": "प्राथमिक उपचार",
    "analysis.next": "आगे क्या करें",
    "analysis.findNearest": "नजदीकी अस्पताल खोजें",
    "analysis.dashboard": "लाइव डैशबोर्ड खोलें",
    "hospitals.title": "स्थिति के अनुसार पास की देखभाल चुनें।",
    "hospitals.copy": "अस्पताल यात्रा समय, दूरी, उपयुक्तता और विभाग के आधार पर क्रमबद्ध हैं।",
    "hospitals.loading": "आपके ट्रायाज के आधार पर पास के अस्पताल खोजे जा रहे हैं...",
    "dashboard.title": "सक्रिय ट्रायाज और देखभाल मार्ग देखें।",
    "dashboard.copy": "अस्पताल डेटा स्थान उपलब्ध होने पर हर 30 सेकंड में अपडेट होता है।",
  },
  bn: {
    "common.language": "ভাষা",
    "common.call112": "১১২-তে কল করুন",
    "common.emergency112": "১১২ জরুরি",
    "nav.home": "হোম",
    "nav.symptoms": "উপসর্গ",
    "nav.reports": "রিপোর্ট",
    "nav.analysis": "বিশ্লেষণ",
    "nav.hospitals": "হাসপাতাল",
    "nav.live": "লাইভ",
    "home.title": "জরুরি চিকিৎসা নির্দেশনা, সবার জন্য সহজ",
    "home.subtitle": "MediRoute AI উপসর্গ বুঝতে, রিপোর্ট পড়তে এবং কাছের উপযুক্ত চিকিৎসা খুঁজতে সাহায্য করে।",
    "home.cta.symptoms": "উপসর্গ পরীক্ষা করুন",
    "home.cta.upload": "রিপোর্ট আপলোড করুন",
    "symptoms.title": "আপনি কী অনুভব করছেন বলুন",
    "symptoms.copy": "যে কোনো ভাষায় বলুন বা লিখুন। ডাক্তারের কাছে যেমন বলতেন তেমন সহজভাবে বলুন।",
    "symptoms.mic.idle": "বলতে ট্যাপ করুন",
    "symptoms.mic.listening": "শোনা হচ্ছে...",
    "symptoms.type": "উপসর্গ লিখুন",
    "symptoms.submit": "বিশ্লেষণে যান",
    "upload.title": "মেডিকেল রিপোর্ট আপলোড করুন",
    "upload.choose": "ফাইল বেছে নিন বা এখানে টানুন",
    "upload.submit": "রিপোর্ট বিশ্লেষণ করুন",
    "analysis.empty.title": "এখনও কোনো বিশ্লেষণ নেই",
    "analysis.findHospitals": "হাসপাতাল খুঁজুন",
    "hospitals.title": "পরিস্থিতির সঙ্গে মিল থাকা কাছের চিকিৎসা বেছে নিন।",
    "dashboard.title": "সক্রিয় ট্রায়াজ ও চিকিৎসা রুট দেখুন।",
  },
  ta: {
    "common.language": "மொழி",
    "common.call112": "112 அழைக்கவும்",
    "common.emergency112": "112 அவசரம்",
    "nav.home": "முகப்பு",
    "nav.symptoms": "அறிகுறிகள்",
    "nav.reports": "அறிக்கைகள்",
    "nav.analysis": "பகுப்பாய்வு",
    "nav.hospitals": "மருத்துவமனைகள்",
    "nav.live": "நேரலை",
    "home.title": "அவசர சிகிச்சை வழிகாட்டல், அனைவருக்கும் எளிதாக",
    "home.subtitle": "MediRoute AI அறிகுறிகளை புரிந்து, அறிக்கைகளை வாசித்து, அருகிலுள்ள பொருத்தமான சிகிச்சையை கண்டறிய உதவுகிறது.",
    "home.cta.symptoms": "அறிகுறிகளை சரிபார்க்கவும்",
    "home.cta.upload": "அறிக்கை பதிவேற்றவும்",
    "symptoms.title": "நீங்கள் என்ன உணர்கிறீர்கள்?",
    "symptoms.copy": "எந்த மொழியிலும் பேசவும் அல்லது தட்டச்சு செய்யவும். மருத்துவரிடம் சொல்வது போல எளிதாக சொல்லுங்கள்.",
    "symptoms.mic.idle": "பேச தட்டவும்",
    "symptoms.mic.listening": "கேட்கிறது...",
    "symptoms.type": "அறிகுறிகளை எழுதவும்",
    "symptoms.submit": "பகுப்பாய்விற்கு தொடரவும்",
    "upload.title": "மருத்துவ அறிக்கைகளை பதிவேற்றவும்",
    "upload.choose": "கோப்புகளை தேர்வு செய்யவும் அல்லது இங்கு இழுக்கவும்",
    "upload.submit": "அறிக்கைகளை பகுப்பாய்வு செய்யவும்",
    "analysis.empty.title": "இன்னும் பகுப்பாய்வு இல்லை",
    "analysis.findHospitals": "மருத்துவமனைகள் காண்க",
    "hospitals.title": "நிலைக்கு பொருத்தமான அருகிலுள்ள சிகிச்சையை தேர்வு செய்யவும்.",
    "dashboard.title": "செயலில் உள்ள டிரையாஜ் மற்றும் சிகிச்சை வழியை கண்காணிக்கவும்.",
  },
  te: {
    "common.language": "భాష",
    "common.call112": "112 కు కాల్ చేయండి",
    "common.emergency112": "112 అత్యవసరం",
    "nav.home": "హోమ్",
    "nav.symptoms": "లక్షణాలు",
    "nav.reports": "రిపోర్టులు",
    "nav.analysis": "విశ్లేషణ",
    "nav.hospitals": "ఆసుపత్రులు",
    "nav.live": "లైవ్",
    "home.title": "అత్యవసర సంరక్షణ మార్గదర్శనం, అందరికీ సులభం",
    "home.subtitle": "MediRoute AI లక్షణాలను అర్థం చేసుకోవడంలో, రిపోర్టులను చదవడంలో, సమీప సరైన సంరక్షణను కనుగొనడంలో సహాయపడుతుంది.",
    "home.cta.symptoms": "లక్షణాలు చెక్ చేయండి",
    "home.cta.upload": "రిపోర్ట్ అప్లోడ్ చేయండి",
    "symptoms.title": "మీకు ఏమి అనిపిస్తుందో చెప్పండి",
    "symptoms.copy": "ఏ భాషలోనైనా మాట్లాడండి లేదా టైప్ చేయండి. డాక్టర్‌కి చెప్పినట్టు సులభంగా చెప్పండి.",
    "symptoms.mic.idle": "మాట్లాడటానికి ట్యాప్ చేయండి",
    "symptoms.mic.listening": "వింటోంది...",
    "symptoms.type": "లక్షణాలు టైప్ చేయండి",
    "symptoms.submit": "విశ్లేషణకు కొనసాగండి",
    "upload.title": "మెడికల్ రిపోర్టులు అప్లోడ్ చేయండి",
    "upload.choose": "ఫైళ్లను ఎంచుకోండి లేదా ఇక్కడికి లాగండి",
    "upload.submit": "రిపోర్టులను విశ్లేషించండి",
    "analysis.empty.title": "ఇంకా విశ్లేషణ లేదు",
    "analysis.findHospitals": "ఆసుపత్రులు కనుగొనండి",
    "hospitals.title": "పరిస్థితికి సరిపోయే సమీప సంరక్షణను ఎంచుకోండి.",
    "dashboard.title": "సక్రియ ట్రయాజ్ మరియు సంరక్షణ మార్గాన్ని గమనించండి.",
  },
  mr: {
    "common.language": "भाषा",
    "common.call112": "112 वर कॉल करा",
    "common.emergency112": "112 आपत्कालीन",
    "nav.home": "होम",
    "nav.symptoms": "लक्षणे",
    "nav.reports": "रिपोर्ट",
    "nav.analysis": "विश्लेषण",
    "nav.hospitals": "रुग्णालये",
    "nav.live": "लाइव्ह",
    "home.title": "तातडीच्या काळजीचे मार्गदर्शन, सर्वांसाठी सोपे",
    "home.subtitle": "MediRoute AI लक्षणे समजणे, रिपोर्ट वाचणे आणि जवळची योग्य काळजी शोधणे सोपे करते.",
    "home.cta.symptoms": "लक्षणे तपासा",
    "home.cta.upload": "रिपोर्ट अपलोड करा",
    "symptoms.title": "तुम्हाला काय जाणवत आहे ते सांगा",
    "symptoms.mic.idle": "बोलण्यासाठी टॅप करा",
    "symptoms.mic.listening": "ऐकत आहे...",
    "symptoms.type": "लक्षणे लिहा",
    "symptoms.submit": "विश्लेषणाकडे जा",
    "upload.title": "वैद्यकीय रिपोर्ट अपलोड करा",
    "upload.choose": "फाइल निवडा किंवा येथे ड्रॅग करा",
    "upload.submit": "रिपोर्टचे विश्लेषण करा",
    "analysis.findHospitals": "रुग्णालये शोधा",
  },
  gu: {
    "common.language": "ભાષા",
    "common.call112": "112 પર કોલ કરો",
    "common.emergency112": "112 ઇમરજન્સી",
    "nav.home": "હોમ",
    "nav.symptoms": "લક્ષણો",
    "nav.reports": "રિપોર્ટ",
    "nav.analysis": "વિશ્લેષણ",
    "nav.hospitals": "હોસ્પિટલ",
    "nav.live": "લાઈવ",
    "home.title": "તાત્કાલિક સારવાર માર્ગદર્શન, દરેક માટે સરળ",
    "home.cta.symptoms": "લક્ષણો તપાસો",
    "home.cta.upload": "રિપોર્ટ અપલોડ કરો",
    "symptoms.title": "તમને શું લાગે છે તે કહો",
    "symptoms.mic.idle": "બોલવા માટે ટેપ કરો",
    "symptoms.type": "લક્ષણો લખો",
    "symptoms.submit": "વિશ્લેષણ પર જાઓ",
    "upload.title": "મેડિકલ રિપોર્ટ અપલોડ કરો",
    "analysis.findHospitals": "હોસ્પિટલ શોધો",
  },
  kn: {
    "common.language": "ಭಾಷೆ",
    "common.call112": "112 ಗೆ ಕರೆ ಮಾಡಿ",
    "common.emergency112": "112 ತುರ್ತು",
    "nav.home": "ಮುಖಪುಟ",
    "nav.symptoms": "ಲಕ್ಷಣಗಳು",
    "nav.reports": "ವರದಿಗಳು",
    "nav.analysis": "ವಿಶ್ಲೇಷಣೆ",
    "nav.hospitals": "ಆಸ್ಪತ್ರೆಗಳು",
    "nav.live": "ಲೈವ್",
    "home.title": "ತುರ್ತು ಆರೈಕೆ ಮಾರ್ಗದರ್ಶನ, ಎಲ್ಲರಿಗೂ ಸುಲಭ",
    "home.cta.symptoms": "ಲಕ್ಷಣ ಪರಿಶೀಲಿಸಿ",
    "home.cta.upload": "ವರದಿ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    "symptoms.title": "ನಿಮಗೆ ಏನು ಅನಿಸುತ್ತಿದೆ ಹೇಳಿ",
    "symptoms.mic.idle": "ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "symptoms.type": "ಲಕ್ಷಣಗಳನ್ನು ಬರೆಯಿರಿ",
    "symptoms.submit": "ವಿಶ್ಲೇಷಣೆಗೆ ಮುಂದುವರಿಸಿ",
    "upload.title": "ವೈದ್ಯಕೀಯ ವರದಿಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    "analysis.findHospitals": "ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ",
  },
  ml: {
    "common.language": "ഭാഷ",
    "common.call112": "112 വിളിക്കുക",
    "common.emergency112": "112 അടിയന്തര",
    "nav.home": "ഹോം",
    "nav.symptoms": "ലക്ഷണങ്ങൾ",
    "nav.reports": "റിപ്പോർട്ടുകൾ",
    "nav.analysis": "വിശകലനം",
    "nav.hospitals": "ആശുപത്രികൾ",
    "nav.live": "ലൈവ്",
    "home.title": "അടിയന്തര പരിചരണ മാർഗ്ഗനിർദ്ദേശം, എല്ലാവർക്കും എളുപ്പം",
    "home.cta.symptoms": "ലക്ഷണങ്ങൾ പരിശോധിക്കുക",
    "home.cta.upload": "റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക",
    "symptoms.title": "നിങ്ങൾക്ക് എന്താണ് തോന്നുന്നത് പറയൂ",
    "symptoms.mic.idle": "സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക",
    "symptoms.type": "ലക്ഷണങ്ങൾ എഴുതുക",
    "symptoms.submit": "വിശകലനത്തിലേക്ക് തുടരുക",
    "upload.title": "മെഡിക്കൽ റിപ്പോർട്ടുകൾ അപ്‌ലോഡ് ചെയ്യുക",
    "analysis.findHospitals": "ആശുപത്രികൾ കണ്ടെത്തുക",
  },
  pa: {
    "common.language": "ਭਾਸ਼ਾ",
    "common.call112": "112 ਤੇ ਕਾਲ ਕਰੋ",
    "common.emergency112": "112 ਐਮਰਜੈਂਸੀ",
    "nav.home": "ਹੋਮ",
    "nav.symptoms": "ਲੱਛਣ",
    "nav.reports": "ਰਿਪੋਰਟਾਂ",
    "nav.analysis": "ਵਿਸ਼ਲੇਸ਼ਣ",
    "nav.hospitals": "ਹਸਪਤਾਲ",
    "nav.live": "ਲਾਈਵ",
    "home.title": "ਤੁਰੰਤ ਦੇਖਭਾਲ ਮਾਰਗਦਰਸ਼ਨ, ਸਭ ਲਈ ਆਸਾਨ",
    "home.cta.symptoms": "ਲੱਛਣ ਜਾਂਚੋ",
    "home.cta.upload": "ਰਿਪੋਰਟ ਅਪਲੋਡ ਕਰੋ",
    "symptoms.title": "ਦੱਸੋ ਤੁਹਾਨੂੰ ਕੀ ਮਹਿਸੂਸ ਹੋ ਰਿਹਾ ਹੈ",
    "symptoms.mic.idle": "ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ",
    "symptoms.type": "ਲੱਛਣ ਲਿਖੋ",
    "symptoms.submit": "ਵਿਸ਼ਲੇਸ਼ਣ ਵੱਲ ਜਾਓ",
    "upload.title": "ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ ਅਪਲੋਡ ਕਰੋ",
    "analysis.findHospitals": "ਹਸਪਤਾਲ ਲੱਭੋ",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggleLang: () => void;
  t: (key: string) => string;
  speechLocale: string;
  languageName: string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  toggleLang: () => {},
  t: (key) => key,
  speechLocale: "en-IN",
  languageName: "English",
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const stored = localStorage.getItem("mediRouteLang") as Lang | null;
    if (languages.some((item) => item.code === stored)) setLangState(stored as Lang);
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const currentLanguage = languages.find((item) => item.code === lang) ?? languages[0];

  const setLang = (next: Lang) => {
    setLangState(next);
    localStorage.setItem("mediRouteLang", next);
  };

  const toggleLang = () => setLang(lang === "en" ? "hi" : "en");

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang,
      speechLocale: currentLanguage.speechLocale,
      languageName: currentLanguage.label,
      t: (key: string) => translations[lang]?.[key] ?? en[key] ?? key,
    }),
    [currentLanguage.label, currentLanguage.speechLocale, lang],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  return useContext(LanguageContext);
}
